[general]
import = [
  "~/.config/alacritty/themes/alacritty-theme/themes/tender.toml"
]

[env]
TERM = "xterm-256color"

[window]

[font]
size = 15
normal = { family = "源ノ角ゴシック Code Jp", style = "N" }
bold = { family = "源ノ角ゴシック Code Jp", style = "B" }
italic = { family = "源ノ角ゴシック Code Jp", style = "N it" }

